/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mederp;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import javafx.scene.control.ComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ilyas
 */
public class userform extends javax.swing.JInternalFrame {

    boolean isNewUser = true;
    ResultSet RSG;
    int userTarget;
    /**
     * Creates new form newuser
     */
    public userform() {
        initComponents();
    }
   
    public userform(int target) throws SQLException{
        initComponents();
        isNewUser = false;
        userTarget = target;
        
        title.setText("Update User");
        adduserbtn.setText("Update User");
        passfield.setEnabled(false);
        jLabel5.setEnabled(false);
        
        RSG = CNX.Select_request("SELECT * FROM users WHERE id = "+target);
        if(RSG.next()) {
            usernamefield.setText(RSG.getString("username"));
            nomfield.setText(RSG.getString("nom"));
            prenomfield.setText(RSG.getString("prenom"));
            passfield.setText(RSG.getString("password"));
            rolecombo.setSelectedItem(RSG.getString("role"));
            specialitycombo.setSelectedItem(RSG.getString("specialite"));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        nomfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prenomfield = new javax.swing.JTextField();
        Prenom = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        specialitycombo = new javax.swing.JComboBox<>();
        rolecombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        errorfield = new javax.swing.JLabel();
        adduserbtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("User Form");

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("New User");
        title.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(title)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title)
                .addGap(20, 20, 20))
        );

        jLabel1.setText("Username");

        jLabel3.setText("Nom");

        prenomfield.setToolTipText("");

        Prenom.setText("Prenom");

        jLabel5.setText("Password");

        jLabel4.setText("Role");

        specialitycombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generaliste", "Gastrologie", "Gynecologie", "Cardiologie", "Chirurgien" }));

        rolecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medecin", "Infirmier", "Secretaire", "Administrateur" }));
        rolecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rolecomboItemStateChanged(evt);
            }
        });

        jLabel6.setText("Specialite");

        errorfield.setForeground(new java.awt.Color(204, 0, 0));

        adduserbtn.setText(" Add new User");
        adduserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(prenomfield, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(Prenom)
                    .addComponent(nomfield, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(usernamefield)
                    .addComponent(jLabel1)
                    .addComponent(passfield))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(specialitycombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rolecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(adduserbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolecombo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialitycombo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Prenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenomfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adduserbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passfield))
                .addGap(18, 18, 18)
                .addComponent(errorfield, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rolecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rolecomboItemStateChanged
        //Polyvalent, Sage-femme, Technicien, Radio, Aide-soignant, Dermatologie, Neurologie
        //Medecin, Infirmier, Secretaire, Administrateur
        if (rolecombo.getSelectedItem().equals("Medecin")){
            specialitycombo.setEnabled(true);
            specialitycombo.removeAllItems();
            String[] spmedecin = {"Generaliste", "Gastrologie", "Gynecologie", "Cardiologie", "Chirurgien"};
            specialitycombo.setModel(new DefaultComboBoxModel<String>(spmedecin));
        } else if(rolecombo.getSelectedItem().equals("Infirmier")) {
            specialitycombo.setEnabled(true);
            specialitycombo.removeAllItems();
            String[] spinfirmier = {"Polyvalent", "Sage-femme", "Technicien", "Radio", "Aide-soignant", "Dermatologie", "Neurologie"};
            specialitycombo.setModel(new DefaultComboBoxModel<String>(spinfirmier));
        } else {
            specialitycombo.removeAllItems();
            specialitycombo.addItem("employee");
            specialitycombo.setEnabled(false);
            
        }
    }//GEN-LAST:event_rolecomboItemStateChanged

    private void adduserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserbtnActionPerformed
        String Username = usernamefield.getText().trim();
        String Nom = nomfield.getText().trim();
        String Prenom = prenomfield.getText().trim();
        String Password = passfield.getText().toString().trim();
        String Role = rolecombo.getSelectedItem().toString();
        String Speciality = specialitycombo.getSelectedItem().toString();
            

        if (Username.isEmpty() || Nom.isEmpty() || Prenom.isEmpty() || Password.isEmpty()){
            errorfield.setText("Please fill all the Fields");
        } else {        
            if (isNewUser){
                String Query = "INSERT INTO users(username, nom, prenom, password, role, specialite) "
                        + "VALUES ('"+Username+"', '"+Nom+"', '"+Prenom+"', '"+Password+"', '"+Role+"', '"+Speciality+"')";
                boolean isDone = CNX.AMS_request(Query);
                if (isDone){
                    JOptionPane.showMessageDialog(null, "User Created Successfully");
                    this.dispose();
                } else {
                    errorfield.setText("Can't add new user to database");

                }
            } else {
                String Query = "UPDATE users SET username = '"+Username+"', nom = '"+Nom+"', prenom = '"+Prenom+"', role = '"+Role+"', specialite = '"+Speciality+"'"
                        + " WHERE id = "+userTarget;
                boolean isDone = CNX.AMS_request(Query);
                if (isDone){
                    JOptionPane.showMessageDialog(null, "User Updated Successfully");
                    this.dispose();
                } else {
                    errorfield.setText("Can't update user in database");

                }
            }
        }
    }//GEN-LAST:event_adduserbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Prenom;
    private javax.swing.JButton adduserbtn;
    private javax.swing.JLabel errorfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomfield;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField prenomfield;
    private javax.swing.JComboBox<String> rolecombo;
    private javax.swing.JComboBox<String> specialitycombo;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
